### ISSUE TITLE
403 Error!!

### ISSUE THREAD

**Issue by 0xhunster** [devanshbatham/autoreport#2]
![image](https://github.com/devanshbatham/autoreport/assets/46501627/8d2367ca-75ad-403a-8c7b-71ece4e817ea)

**Comment by devanshbatham** [comment]
The poe reversed API does not works, will archive this repo soon (in case there is no workaround found)

**Comment by 0xhunster** [comment]
this repo just awesome brother. could you resolve this? or add the chatgpt?

**Comment by 0xhunster** [comment]
Hello boss.......
